# Generated by Django 5.0.1 on 2024-01-25 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_searchlog_genlog"),
    ]

    operations = [
        migrations.AlterModelOptions(name="customuser", options={},),
        migrations.AlterModelTable(name="customuser", table="auth_customer",),
    ]
