# Generated by Django 5.0.1 on 2024-02-12 20:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_customuser_options_alter_customuser_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="Issue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("issue", models.CharField(max_length=100)),
                ("comment", models.CharField(max_length=1000)),
                ("target", models.CharField(max_length=100)),
                ("prompt", models.CharField(max_length=100)),
                ("analogy", models.CharField(max_length=10000)),
                ("pid", models.CharField(max_length=100)),
                ("solved", models.BooleanField(default=False)),
                ("admin_comment", models.CharField(max_length=1000)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
