# Generated by Django 5.0.1 on 2024-02-13 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_issue"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="admin_comment",
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name="issue",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
