# Generated by Django 5.0.1 on 2024-03-01 03:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_customuser_free_openai_api_key"),
    ]

    operations = [
        migrations.RenameField(
            model_name="issue", old_name="comment", new_name="detail",
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("comment", models.CharField(max_length=1000)),
                ("admin_selected", models.BooleanField(default=False)),
                ("admin_comment", models.CharField(blank=True, max_length=1000)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
