# Generated by Django 5.0.1 on 2024-03-01 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_rename_comment_issue_detail_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="analogy",
            field=models.CharField(default="test", max_length=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="comment",
            name="pid",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="comment",
            name="prompt",
            field=models.CharField(default="test", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="comment",
            name="target",
            field=models.CharField(default="test", max_length=100),
            preserve_default=False,
        ),
    ]
