# Generated by Django 5.0.1 on 2024-03-14 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_comment_analogy_comment_pid_comment_prompt_and_more"),
    ]

    operations = [
        migrations.DeleteModel(name="Comment",),
    ]
