# Generated by Django 5.0.1 on 2024-03-17 02:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_delete_comment"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("comment", models.CharField(max_length=1000)),
                ("admin_selected", models.BooleanField(default=False)),
                ("admin_comment", models.CharField(blank=True, max_length=1000)),
                ("target", models.CharField(max_length=100)),
                ("prompt", models.CharField(max_length=100)),
                ("analogy", models.CharField(max_length=10000)),
                ("pid", models.CharField(max_length=100)),
                (
                    "replyTo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="users.comment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
