# Generated by Django 5.0.1 on 2024-03-17 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="notification",
            field=models.BooleanField(default=False),
        ),
    ]
