# Generated by Django 5.0.1 on 2024-03-25 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_rename_analogies_searchlog_prompt_searchlog_tmp"),
    ]

    operations = [
        migrations.RenameField(
            model_name="searchlog", old_name="tmp", new_name="temp",
        ),
    ]
