# Generated by Django 4.2.10 on 2024-03-25 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_rename_tmp_searchlog_temp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="searchlog", name="temp", field=models.CharField(max_length=10),
        ),
    ]
