# Generated by Django 4.2.10 on 2024-04-05 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_alter_searchlog_temp"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "ADMIN"),
                    ("STUDENT", "STUDENT"),
                    ("TEACHER", "TEACHER"),
                    ("EXPERT", "EXPERT"),
                ],
                default="STUDENT",
                max_length=100,
            ),
        ),
    ]
