# Generated by Django 4.2.10 on 2024-04-05 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0015_customuser_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="points",
            field=models.IntegerField(default=0),
        ),
    ]
