# Generated by Django 4.2.10 on 2024-07-09 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0017_searchlog_ip_alter_comment_admin_selected"),
    ]

    operations = [
        migrations.AddField(
            model_name="genlog",
            name="model",
            field=models.CharField(default="gpt-3", max_length=100),
        ),
        migrations.AlterField(
            model_name="comment", name="analogy", field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="genlog", name="analogy", field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="issue", name="analogy", field=models.TextField(),
        ),
    ]
