# Generated by Django 4.2.10 on 2024-07-11 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0018_genlog_model_alter_comment_analogy_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="prompt",
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="issue", name="prompt", field=models.CharField(max_length=1000),
        ),
    ]
